### ISSUE TITLE
Segfault when specifying proxy_connect_header

### ISSUE THREAD

**Issue by annrajan** [cloudprober/cloudprober#930]
**Describe the bug**
When specifying a key/value pair for `proxy_connect_header` ([documentation link](https://cloudprober.org/docs/config/probes/#cloudprober_probes_http_ProbeConf_ProxyConnectHeaderEntry)), I get a segfault with the error `panic: assignment to entry in nil map`. 

The header I'm trying to add is of the following shape:
```
proxy_connect_header: {
        key: "Proxy-Authorization"
        value: "Basic ..."
}
```

**Cloudprober Version**
0.13.7

**To Reproduce**
I believe this can be reproduced for any value of proxy_connect_header (provided there's a proxy_url value as well):
```
    http_probe {
      method: GET
      protocol: HTTPS
      proxy_url: "..."
      proxy_connect_header: {
        key: "Proxy-Authorization"
        value: "Basic ..."
      }
    }
```

**Additional context**
The root cause seems to be this line: https://github.com/cloudprober/cloudprober/blob/v0.13.7/probes/http/http.go#L129.
I believe we need something like `transport.ProxyConnectHeader = http.Header{}` before the for loop. 

Full stack trace:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
net/textproto.MIMEHeader.Add(...)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/net/textproto/header.go:15
net/http.Header.Add(...)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/net/http/header.go:31
github.com/cloudprober/cloudprober/probes/http.(*Probe).getTransport(0x14000a82c00)
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/probes/http/http.go:129 +0x580
github.com/cloudprober/cloudprober/probes/http.(*Probe).Init(0x14000a82c00, {0x14000922954?, 0x0?}, 0x0?)
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/probes/http/http.go:221 +0x418
github.com/cloudprober/cloudprober/probes.initProbe(0x1400090c640, 0x1400095f0a0)
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/probes/probes.go:176 +0x720
github.com/cloudprober/cloudprober/probes.CreateProbe(0x1400090c640, 0x1400095f0a0)
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/probes/probes.go:103 +0x2c
github.com/cloudprober/cloudprober/prober.(*Prober).addProbe(0x14000aac500, 0x1400090c640)
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/prober/prober.go:119 +0x2d4
github.com/cloudprober/cloudprober/prober.(*Prober).Init(0x14000aac500, {0x102b45ca0, 0x14000a9dae0}, 0x100ed1898?, 0x1400072dc08?)
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/prober/prober.go:187 +0x460
github.com/cloudprober/cloudprober.initWithConfigSource({0x102b428f0, 0x14000114360})
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/cloudprober.go:235 +0x4dc
github.com/cloudprober/cloudprober.InitWithConfigSource({0x102b428f0?, 0x14000114360?})
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/cloudprober.go:156 +0x24
github.com/cloudprober/cloudprober.Init()
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/cloudprober.go:152 +0x2c
main.main()
        /private/tmp/cloudprober-20240826-4617-clkp8p/cloudprober-0.13.7/cmd/cloudprober/main.go:150 +0x500
```

**Comment by manugarg** [comment]
Thanks for filing this issue, @annrajan. Looks like this has never worked (it was added in June this year). I've sent #932 to fix.

**Comment by manugarg** [comment]
@annrajan I released Cloudprober only a couple of days back. Next release is at least a few weeks away (since this has never worked before, it doesn't necessitate an emergency release). In the meantime, you could use the unreleased docker image:
https://github.com/cloudprober/cloudprober/wiki/Unreleased-Binaries

**Comment by annrajan** [comment]
Thank you @manugarg!

**Comment by annrajan** [comment]
@manugarg any chance you could cherry pick this fix onto the existing 0.13.8 release and cut an 0.13.8.1 release we could use?

**Comment by manugarg** [comment]
@annrajan 

I've avoided creating release branches so far, and would like to continue that 😄 

I've just added a new stable tag to the docker images with the proxy-connect-header fix: `v0.13.8-1`. Will that be good enough?

**Comment by annrajan** [comment]
Thanks @manugarg - unfortunately we won't be able to work with just the tagged image, we need to use a release for our current setup. When is the next release planned?

**Comment by annrajan** [comment]
^bump @manugarg in case you didn't get a chance to see the above

**Comment by manugarg** [comment]
@annrajan, sorry, closed issues don't show up prominently. Next release is further pushed back as there have been no other changes. To solve your problem, can I just add a tag. IIUIC, I think your system might be downloading the repository at a tagged version. Let me know if that helps, otherwise I'll figure something out.
